version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      aws_cdk:
        patterns:
          - "aws-cdk*"
      vitest:
        patterns:
          - vitest
          - "@vitest/*"
