name: document
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: document-${{ github.ref }}
  cancel-in-progress: true
jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/setup
      - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
      - uses: homebrew/actions/setup-homebrew@master
      - run: brew install deno
      - run: node --run build:doc
      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: docs
      - uses: actions/deploy-pages@decdde0ac072f6dcbe43649d82d9c635fff5b4e4 # v4.0.4
        if: github.ref == 'refs/heads/main'
